apiVersion: "ecr.services.k8s.aws/v1alpha1"
kind: Repository
metadata:
    name: "repo"
    namespace: default 
spec:
  name: test-repo
  encryptionConfiguration:
    encryptionType: AES256
  tags:
  - key: "me"
    value: "Ivo"
